#!/bin/sh
SRC=$0
CWD=$PWD
cd "$(dirname "$SRC")"
LINK=$(readlink "$(basename "$SRC")")
while [[ -n "$LINK" ]]; do
    cd "$(dirname "$LINK")"
    LINK=$(readlink "$(basename "$SRC")")
done
ROOT="$PWD"
cd "$CWD"
exec "$ROOT/venv/bin/python3" "$ROOT/src/cli_start.py" "$@"
